### ISSUE TITLE
どこに行く？

### ISSUE THREAD

**Issue by arayaryoma** [kosen10s/excursion#1]
行く場所を決める。
温泉旅館なのは確定。

日程( #3 )に依存

**Comment by denari** [comment]
https://nct-2010s.slack.com/files/denari/F0J8EKDB2/___________________________www.txt

**Comment by suzuyoshi9** [comment]
箱根に決定したぞ！

何か行きたい場所とかのことは別issueで挙げる？

**Comment by denari** [comment]
別issueにしましょうそうしましょう
