### ISSUE TITLE
なにで行く？

### ISSUE THREAD

**Issue by arayaryoma** [kosen10s/excursion#2]
交通手段を決める。
場所によって変わるので #1 に依存する。

**Comment by denari** [comment]
https://nct-2010s.slack.com/files/denari/F0J8EKDB2/___________________________www.txt
見た感じ正直車は厳しいかなあ

**Comment by suzuyoshi9** [comment]
車でなければ、箱根フリーパスを使う感じになるか…？
交通手段：電車＋バス
http://www.odakyu.jp/train/couponpass/hakone/

**Comment by denari** [comment]
それで行こう!(と、いいつつ、closeはせず、誰かが同意してcloseしてくれるのを待つ)

**Comment by suzuyoshi9** [comment]
電車とバスで行きましょう
