### ISSUE TITLE
いつ何泊で行く？

### ISSUE THREAD

**Issue by arayaryoma** [kosen10s/excursion#3]
いつ、何泊で行くか決める。

**Comment by denari** [comment]
![2016-01-13 20 48 22](https://cloud.githubusercontent.com/assets/5387939/12293469/17a0c13a-ba37-11e5-97c5-a128a51c4e82.png) 

泊数だけ決まったことをメモ

**Comment by suzuyoshi9** [comment]
3/12 - 3/14　2泊3日(無理な人は1泊2日) でfix。
