### ISSUE TITLE
参加者の募集

### ISSUE THREAD

**Issue by arayaryoma** [kosen10s/excursion#8]
場所 #1 日程 #3 (参加費 #7 ) が確定したら参加者を募る

**Comment by denari** [comment]
そうだ、これどうやってやんの??
slack外のメンバーに対してどれ位オープンにするかにもよる気がしていて、

【① slackに入ってない人もWelcome!!!!な場合】
Doorkeeperがよさそう(LT会でも使ってるから一回でもLT会に参加している人に自動でメールが飛ぶの、絶対良い)

【② いや、流石に旅行だから水注されちゃ困る。な場合】
DoorkeeperだとダメだからSlackのCHANNELに入ってもらうなどの対処が考えられる。

どっちだろう。正直オレはかなり迷っていて「こっちがいい」って言えないかな。

**Comment by arayaryoma** [comment]
個人的には
・LT会に1回以上参加したことがある
・旅行参加者の誰かしらと面識がある
のどちらかの条件は満たしてほしい。
水注されると困るってよりも、信頼関係の問題で。

Doorkeeperでいいと思うよ〜。
流石に知り合いが誰一人いない旅行に飛び込んでくる人いないでしょ

**Comment by denari** [comment]
いいね!

**Comment by suzuyoshi9** [comment]
最大人数は12人 (#10 より)

**Comment by denari** [comment]
https://kosen10s.doorkeeper.jp/events/39580 done :tada:
