### ISSUE TITLE
旅館の候補を出す

### ISSUE THREAD

**Issue by arayaryoma** [kosen10s/excursion#9]
#1 #3 に依存

**Comment by denari** [comment]
1. https://www.kanponoyado.japanpost.jp/hakone/
2. http://www.hakone-yumotohotel.com/
3. http://www.ichinoyu.co.jp/index.php
4. http://www.kitetsu-hotel.jp/hakone/index.html
5. http://www.hakonebizan.com/
6. http://www.sunterrace.co.jp/

候補出た。まとめた。
